language: python
env:
  global:
    - REQUIREMENTS=requirements.txt
    - TEST_REQUIREMENTS=social/tests/requirements.txt
python:
  - "2.6"
  - "2.7"
  - "pypy"
matrix:
  include:
    - python: "3.3"
      env:
          - REQUIREMENTS=requirements-python3.txt
          - TEST_REQUIREMENTS=social/tests/requirements-python3.txt
    - python: "3.4"
      env:
          - REQUIREMENTS=requirements-python3.txt
          - TEST_REQUIREMENTS=social/tests/requirements-python3.txt
install:
  - "python setup.py -q install"
  - "travis_retry pip install -r $REQUIREMENTS"
  - "travis_retry pip install -r $TEST_REQUIREMENTS"
script:
  - "nosetests --with-coverage --cover-package=social --where=social/tests"
